### ISSUE TITLE
请问这个主板能换网卡吗？

### ISSUE THREAD

**Issue by leonfg** [FisherWY/Hackintosh#1]
想买这个板子hackintosh，想问下大神是否了解这个板子能不能换无线模块？

**Comment by xuchaofriend** [comment]
我想如果可以换黑苹果兼容网卡就好了

**Comment by FisherWY** [comment]
非常抱歉，我没有开仓库issue通知，因此现在才看到这个问题😅
这款主板的一体IO背板和无线网卡都是可以拆掉的，因此是可以换无线模块的，目前我知道的有以下3种方案：
1. 上淘宝买苹果电脑的拆机网卡，然后接上转接线就可以正常免驱工作了。这种方法使用的网卡型号好像是博通的94360cs2，因为B360i的IO背板是双天线的，所以需要买双天线的版本，不然的话IO背板是装不回去的。
2. 第二种方法就需要牺牲一个m2接口，IO背板也能完美装回去。先把AC9560拆下来，同样的也是买苹果电脑的拆机网卡，博通94360cs2 943602cs 94360cd等。博通的网卡都可以免驱使用的，但是这些网卡都有4天线，需要把其中的两根天线隐藏起来，只把其中的两根接到IO背板的天线接口上。
3. 第三种方法就是买博通的dw1830，这张网卡可以完美更换到AC9560的插槽上，不需要转接线。但是蓝牙驱动好像是要自己折腾一下，这个我没有去研究了，你可以看看别人的贴子。

**Comment by FisherWY** [comment]
现在Intel蓝牙和无线网卡已经有驱动可以使用了，仓库名叫[OpenIntelWireless](https://github.com/OpenIntelWireless)，根据文档配置驱动即可。
