### ISSUE TITLE
大佬，同样主板我装双系统，你会出现切换mac或win时进入安全模式的情况吗？

### ISSUE THREAD

**Issue by sqh-world** [FisherWY/Hackintosh#4]
安全模式显示the system has posted in safe mode

**Comment by FisherWY** [comment]
- 这个问题主要是由于Apple RTC和其他主板的传统RTC或更新的AWAC不兼容导致的
- 问题产生的具体原因和通用的解决方法可以参考Xjn大佬的这篇博客：[RTC综述](https://blog.xjn819.com/post/rtc-issues-related-to-oc.html)
- 我是如何解决这个问题的：打开OC的配置文件，在`Kernel`设置页面，勾选`DisableRtcChecksum`，保存重启就不会进入安全模式了

**Comment by PanjiLovePanda** [comment]
> * 这个问题主要是由于Apple RTC和其他主板的传统RTC或更新的AWAC不兼容导致的
> * 问题产生的具体原因和通用的解决方法可以参考Xjn大佬的这篇博客：[RTC综述](https://blog.xjn819.com/post/rtc-issues-related-to-oc.html)
> * 我是如何解决这个问题的：打开OC的配置文件，在`Kernel`设置页面，勾选`DisableRtcChecksum`，保存重启就不会进入安全模式了

**Comment by cloudmere** [comment]
> * 这个问题主要是由于Apple RTC和其他主板的传统RTC或更新的AWAC不兼容导致的
> * 问题产生的具体原因和通用的解决方法可以参考Xjn大佬的这篇博客：[RTC综述](https://blog.xjn819.com/post/rtc-issues-related-to-oc.html)
> * 我是如何解决这个问题的：打开OC的配置文件，在`Kernel`设置页面，勾选`DisableRtcChecksum`，保存重启就不会进入安全模式了

亲测有用，谢谢大佬！
